#name : Static Lib Makefile
# expand-env: ((yas/indent-line 'fixed))
# --
NAME	= lib${1:pgm}.a

SUBLIBS	= ${2:libmy/libmy.a}

CC	= gcc
RM	= rm -f

CFLAGS	+= -g -O0
CFLAGS	+= -Wextra -Wall -Werror=implicit
CFLAGS	+= -Wno-unused-parameter
CFLAGS	+= -ansi -pedantic

CFLAGS	+= $(patsubst %,-I%,$(dir $(SUBLIBS)))
CFLAGS	+= $0

SRCS	= $(wildcard *.c)
HDRS	= $(wildcard *.h)
OBJS	= $(SRCS:.c=.o)

all:	$(NAME)

$(NAME):		$(NAME)($(OBJS))
$(NAME)($(OBJS)):	$(OBJS)
$(OBJS):		$(SUBLIBS) $(HDRS)

clean:
	$(RM) $(OBJS)
distclean:	clean
	for i in $(dir $(SUBLIBS)); do $(MAKE) -C $$i $@; done
	$(RM) $(NAME)
fclean:	distclean
re:	distclean all


$(SUBLIBS):
	$(MAKE) -C $(dir $@) $(notdir $@)

.PHONY:	all clean distclean fclean re

